#version 430 core
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

uniform float iTime;

layout(binding = 0, rgba32f) uniform image2D fluidTexture;

void main()
{
    // Calculate the position in the texture
    ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
    vec4 color = vec4(0,0,0,0);
    // Store the updated color back to the texture
    imageStore(fluidTexture, texCoord, color);
}